### ISSUE TITLE
只支持原生微信小程序吗

### ISSUE THREAD

**Issue by YcZzy** [jaluik/wx-ci#3]

**Comment by jaluik** [comment]
是的，只是对小程序原生ci相关的api进行的一层封装

**Comment by YcZzy** [comment]
像支持taro之类的有计划嘛

**Comment by jaluik** [comment]
> 像支持taro之类的有计划嘛

这个跟框架没关系，如果使用taro的话，只需要把preCommand这个配置项改成taro的打包命令就可以了
